apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-a-deployment
    # run: service-a-deployment
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-deployment
  template:
    metadata:
      labels:
        app: service-a-deployment
    spec:
      containers:
      - image: harishnshetty/servicea:latest
        name: service-a
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"
        - name: SERVICE_B_URI
          value: "http://b-service.dev"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-b-deployment
    # run: service-b-deployment
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-deployment
  template:
    metadata:
      labels:
        app: service-b-deployment
    spec:
      containers:
      - image: aharishnshetty/serviceb:latest
        name: service-b
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector.tracing:14268/api/traces"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    job: node-api
    app: b-service
  name: b-service
spec:
  ports:
  - name: b-service-port
    port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    app: service-b-deployment

